baseURL: "https://akshay-hegde.github.io/" 
title: Akshay Hegde
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Education
          url: education/
          weight: 3 
        - name: Teaching
          url: teaching/
          weight: 4
        - name: Visits
          url: visits/
          weight: 5  
        # - name: Academics
        #   url: courses/
        #   weight: 4
        - name: Miscellaneous
          url: miscellaneous/
          weight: 6
          children:  # This defines the sub-pages under Miscellaneous
            - name: Links
              url: miscellaneous/links/  # You can adjust the URL as needed
              weight: 1
            - name: Frozen Moments
              url: miscellaneous/musings/  # You can adjust the URL as needed
              weight: 2

params:
    description: " Probability"
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Akshay Hegde
          subtitle: "I'm a PTA assistant Professor at NUS. 
                    
                    <br> 
                    <br>
                    Contact: akshaychipgi@gmail.com

              
                    <br>
                    Office: 05-10, S17 
                            Department of Mathematics
                            10, Lower Kent Ridge road
                            Singapore "
          imageUrl: "profile_picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Meghana Bhat
          buttons:
            - name: Research
              url: papers/
            - name: Education
              url: education/ 
            - name: Teaching
              url: teaching/
            - name: Visits
              url: visits/   
            # - name: Academics
            #   url: courses/
            - name: Miscellaneous
              url: miscellaneous/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: CV
          url: https://drive.google.com/file/d/1Jwz6Hqx0jGf9El_Yoim0qFJTNAJ77CWN/view?usp=sharing
        - name: Email
          url: mailto:mbhat.math@gmail.com
        # - name: GitHub
        #   url: https://github.com/MeghanaBht
        - name: LinkedIn
          url: https://www.linkedin.com/in/meghanamath

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Meghana Bhat"
      icon: faviconM.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
