baseURL: "https://akshay-hegde-math.github.io/" 
title: Akshay Hegde
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Short Bio
          url: bio/
          weight: 3 
        - name: Teaching
          url: teaching/
          weight: 4
        #- name: Visits
        #  url: visits/
        #  weight: 5  
        # - name: Academics
        #   url: courses/
        #   weight: 4
        - name: Miscellaneous
          url: miscellaneous/
          weight: 5
          children:  # This defines the sub-pages under Miscellaneous
            - name: Links
              url: miscellaneous/links/  # You can adjust the URL as needed
              weight: 1
            - name: Frozen Moments
              url: miscellaneous/musings/  # You can adjust the URL as needed
              weight: 2

params:
    description: " Probability"
    # author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Akshay Hegde
          subtitle: "I'm a Peng Tsu Ann assistant professor (visiting fellow) at the Department of Mathematics at NUS, Singapore. 
                    
                    <br> 
                    <br>
                    Contact: akshay.hegde@nus.edu.sg

              
                    <br>
                    Office: 05-10, S17 <br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                            Department of Mathematics <br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                            10, Lower Kent Ridge road <br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                            Singapore "
          imageUrl: "profile_picture.jpeg"
          imageWidth: 200
          imageHeight: 220
          imageTitle: Akshay Hegde
          buttons:
            - name: Research
              url: research/
            - name: Short Bio
              url: bio/ 
            - name: Teaching
              url: teaching/
            # - name: Visits
            #  url: visits/   
            # - name: Academics
            #   url: courses/
            #- name: Miscellaneous
            #  url: miscellaneous/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: CV
          url: /Users/akshayhegde/Documents/akshay-hegde.github.io/static/CV_Akshay.pdf
        - name: Email
          url: mailto:akshay.hegde@nus.edu.sg
        - name: LinkedIn
          url: https://www.linkedin.com/in/akshay-hegde-045984b9/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Akshay Hegde"
      icon: faviconM.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
